Now uses iptables to restrict database access and outputs status to syslog.
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@15857 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/ssg-dbstatus-initd b/etc/ssg-dbstatus-initd
--- a/etc/ssg-dbstatus-initd
+++ b/etc/ssg-dbstatus-initd
@@ -1,16 +1,16 @@
 #!/bin/bash
 #
-# Startup script for the Secure Span Gateway Server db status support
+# Startup script for the SecureSpan Gateway Server db status support
 #
-# Disallow DB connections while database replication catches up to the
-# other node.
+# Disallow TCP/3306 DB connections while database replication catches up to
+# the other node.
 #
 # We sleep before any checking to ensure that replication logs are being
 # copied (else the timestamp could be up to date even though the DB is
 # still not fully replicated)
 #
 # chkconfig: - 98 02
-# description: Layer7's Secure Span Gateway Db Status Daemon
+# description: Layer 7 Technologies SecureSpan Gateway Db Status Daemon
 # processname: ssg-dbstatus
 
 # Source function library.
@@ -25,13 +25,16 @@ MYSQL="/usr/bin/mysql"
 MYSQL_OPTS=""
 MYSQL_DEFAULT_OPTIONS="/root/.my.cnf"
 TIME_DESIRED=15
+LOGGER="/usr/bin/logger"
 PID_FILE="/var/run/${PROG}.pid"
+IPTABLES="/sbin/iptables"
+IPTABLES_RULE="INPUT -m tcp -p tcp --dport 3306 -j REJECT --reject-with tcp-reset"
 
 if [ ! -f "${HOME}/.my.cnf" ] && [ -f "${MYSQL_DEFAULT_OPTIONS}" ] ; then
     MYSQL_OPTS="--defaults-extra-file=${MYSQL_DEFAULT_OPTIONS} ${MYSQL_OPTS}"
 fi
 
-export MYSQL MYSQL_OPTS TIME_DESIRED
+export MYSQL MYSQL_OPTS TIME_DESIRED IPTABLES IPTABLES_RULE
 
 # Check if replication is enabled
 checkRequired() {
@@ -46,6 +49,10 @@ checkRequired() {
 # Configuration checks, ensure process list output is usable and we can
 # see the 'system user'
 checkConfigured() {
+    if [ ! -f "${IPTABLES}" ] ; then
+        echo "iptables [${IPTABLES}] not found."
+        return 1
+    fi
     if [ ! -f "${MYSQL}" ] ; then
         echo "MySQL client [${MYSQL}] not found."
         return 1
@@ -66,6 +73,28 @@ checkConfigured() {
         return 1
     fi
     return 0
+}
+
+# Logging
+report() {
+    REPORT="${1}"
+    if [ -f "${LOGGER}" ] ; then
+        "${LOGGER}" -t "${PROG}" "${REPORT}"
+    fi
+}
+
+# Disable MySQL
+disableTcpConnections() {
+    # Insert iptables rule
+    "${IPTABLES}" -I ${IPTABLES_RULE}
+    return ${?}
+}
+
+# Enable MySQl
+enableTcpConnections() {
+    # Delete iptables rule
+    "${IPTABLES}" -D ${IPTABLES_RULE}
+    return ${?}
 }
 
 # Service start
@@ -93,28 +122,42 @@ start () {
         exit 1
     fi
 
-    MAX_CONNECTIONS=$("${MYSQL}" ${MYSQL_OPTS} -N -B -e "select @@max_connections;" 2>/dev/null)
-    export MAX_CONNECTIONS
+    disableTcpConnections
+    if [ ${?} -eq 1 ] ; then
+        echo -n $"${PROG} starting: "
+        failure
+        echo
+        exit 1
+    fi
 
-    CONTINUE_FILE=$(mktemp -t myreplflag.XXXXXXXXXXXX)
+    export CONTINUE_FILE=$(mktemp -t myreplflag.XXXXXXXXXXXX)
     # Wait for replication to complete
     (  
         # record pid
         /bin/bash -c 'echo $PPID' > "${PID_FILE}"
 
+        report "DB replication status check starting."
+
         # -5 since we sleep for 5 in the loop
         sleep $((TIME_DESIRED-5))
         COUNT=1
-        echo "set global max_connections=1;"
-        while [ $COUNT -le 48 ] && [ -f "${CONTINUE_FILE}" ] ; do 
+        while [ $COUNT -le 48 ] && [ -f "${CONTINUE_FILE}" ] ; do
             sleep 5
             echo "show processlist;"
             COUNT=$((COUNT+1))
         done;
-        echo "set global max_connections=${MAX_CONNECTIONS};"
+
+        if [ ! -f "${CONTINUE_FILE}" ] ; then
+            report "DB replication is up to date."
+        else
+            report "Exiting due to timeout."
+            rm -f "${CONTINUE_FILE}"
+        fi
+
+        enableTcpConnections
     ) | "${MYSQL}" ${MYSQL_OPTS} -B -N -t -n 2>/dev/null | (
         # Add trap to ensure max connections reset on (subshell) exit
-        trap "{ \"${MYSQL}\" ${MYSQL_OPTS} -N -B -e \"set global max_connections=${MAX_CONNECTIONS};\" &>/dev/null; }" EXIT
+        trap "{ enableTcpConnections &>/dev/null; }" EXIT
         TIME_A=-1
         TIME_B=-1
 
@@ -144,7 +187,10 @@ start () {
 
                         if [ ${TIME} -le ${TIME_DESIRED} ] ; then
                             # Done, so exit
+                            report "DB replication time is ${TIME}, replication up to date."
                             rm -f "${CONTINUE_FILE}"
+                        else
+                            report "DB replication time is ${TIME}"
                         fi
 
                         # Reset times
@@ -160,7 +206,7 @@ start () {
     ) &
 
     echo -n $"${PROG} starting: "
-    # sleep to allow DB connections to be enabled if everything is OK
+    # sleep to allow tcp connections to be enabled if everything is OK
     sleep ${TIME_DESIRED}
     success
     echo
