build changes + rpm changes for setting up partitioning and not leaving so much work for the migrator. fixes to startup scripts (invoke firewall changes per partition now)
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@15007 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/ssg-initd b/etc/ssg-initd
--- a/etc/ssg-initd
+++ b/etc/ssg-initd
@@ -23,9 +23,17 @@ ssguser="gateway"
 prog="SSG"
 tries=3
 count=0
+
 USER=`whoami`
-partition_base="$SSG_HOME/etc/conf/partitions/"
-partition_control="partitionControl.sh"
+PARTITION_BASE="$SSG_HOME/etc/conf/partitions/"
+PARTITION_CONTROL="$SSG_HOME/bin/partitionControl.sh"
+SINGLE_PARTITION=""
+
+# See how we were called.
+if [ $USER != "root" ] ; then
+    echo"Need to be root or $ssguser to run this script";
+    exit
+fi
 
 # handle 3 different cases:
 # Run as root, run as a regular user, run as same user as ssguser.
@@ -33,110 +41,114 @@ partition_control="partitionControl.sh"
 # terminal
 
 start() {
-	find_tomcat
-	if [ -n "$pid" ] ; then
-		echo "At least one SSG Partition is already running. Please stop and restart."
-		exit
-	fi
-	find_partitions
+    find_single_partition "$1"
+    if [ -n "${SINGLE_PARTITION}" ] ; then
+	    start_ssg ${SINGLE_PARTITION}
+	else
+        find_tomcat
+        if [ -n "$pid" ] ; then
+            echo "At least one SSG Partition is already running. Please stop and restart."
+            exit
+        fi
 
-	for partition_dir in ${ALL_PARTITIONS}
-	do
-		echo -n $"Starting $prog (`basename ${partition_dir}`): "
-		. $partition_base/$partition_dir/partition_defs.sh true ${PARTITION_COUNT}
-		JAVA_OPTS="${ORIGINAL_JAVA_OPTS} ${partition_opts}"
-		if [ "$USER" = "root" ]; then
-        		su $ssguser -c "sh $partition_base/$partition_dir/$partition_control start" &>/dev/null <&-
-        		RETVAL=$?
-		elif [ "$USER" = "$ssguser" ]; then
-			sh $partition_base/$partition_dir/$partition_control start &>/dev/null <&-
-			RETVAL=$?
-		else
-			echo"Need to be root or $ssguser to run this script";
-			exit
-		fi	
-        	echo
-	done
+        for partition_dir in ${ALL_PARTITIONS}
+        do
+            start_ssg ${partition_dir}
+        done
         # [ $RETVAL = 0 ] && touch /var/lock/subsys/ssg
         return $RETVAL
+    fi
 }
 
 stop() {
-	find_tomcat;
-	if [ -z "$pid" ] ; then
-		echo "No SSG Partitions are Currently Running"
-		return
-	fi
-	find_partitions
-	for partition_dir in $ALL_PARTITIONS
-	do
-		echo -n $"Stopping $prog (`basename $partition_dir`): "
-		if [ "$USER" = "root" ]; then
-        		su - $ssguser -c "$partition_base/$partition_dir/$partition_control stop -force" > /dev/null 2>&1
-        		RETVAL=$?
-		elif [ "$USER" = "$ssguser" ]; then
-			$partition_base/$partition_dir/$partition_control stop > /dev/null 2>&1
-			RETVAL=$?
-		else
-			echo "Need to be root or $ssguser to run this script";
-			exit
-		fi
-	done
-	#after shutting down all the partitions, make sure they are all fully stopped
-	if [ $RETVAL = 0 ]; then 
-		sleep 7;
-		find_tomcat;
-		if [ -z "$pid" ] ; then
-			echo "Success"
-			return
-		fi
-		count=`expr $count + 1`
-		if [ "$count" -gt "$tries" ]; then
-			reallystop
-			return
-		fi  
-		stop;
-	
-	else
-		sleep 2;
-		count=`expr $count + 1`
-		if [ "$count" -gt "$tries" ]; then
-			reallystop
-			return
-		fi  
-		stop;
-	fi 
-	echo
+    find_single_partition "$1"
+    if [ -n "${SINGLE_PARTITION}" ] ; then
+        stop_ssg ${SINGLE_PARTITION}
+    else
+        find_tomcat;
+        if [ -z "$pid" ] ; then
+            echo "No SSG Partitions are Currently Running"
+            return
+        fi
 
+        for partition_dir in $ALL_PARTITIONS
+        do
+            stop_ssg ${partition_dir}
+        done
+        #after shutting down all the partitions, make sure they are all fully stopped
+        if [ $RETVAL = 0 ]; then
+            sleep 7;
+            find_tomcat;
+            if [ -z "$pid" ] ; then
+                echo "Success"
+                return
+            fi
+            count=`expr $count + 1`
+            if [ "$count" -gt "$tries" ]; then
+                reallystop
+                return
+            fi
+            stop;
+	    else
+		    sleep 2;
+            count=`expr $count + 1`
+            if [ "$count" -gt "$tries" ]; then
+                reallystop
+                return
+            fi
+		    stop;
+	    fi
+    fi
+    echo
 	return $RETVAL
+}
+
+stop_ssg() {
+    which_partition=$1
+    echo -n $"Stopping $prog (`basename "${which_partition}"`): "
+	su $ssguser -c "sh $PARTITION_CONTROL stop ${which_partition} -force" > /dev/null 2>&1
+    RETVAL=$?
+}
+
+start_ssg() {
+    which_partition=$1
+    echo -n $"Starting $prog (`basename "${which_partition}"`): "
+
+    su $ssguser -c "sh $PARTITION_CONTROL start ${which_partition}" &>/dev/null <&-
+    RETVAL=$?
+    echo
 }
 
 find_tomcat() {
 	pid=`pidof ${JAVA_HOME}/bin/java`
 }
 
-
-find_partitions() {
-	ALL_PARTITIONS=`ls ${SSG_HOME}/etc/conf/partitions/ | grep -v template_`
-	PARTITION_COUNT=`echo ${ALL_PARTITIONS} | wc -w`
+find_single_partition() {
+    if [ -n "${1}" ] ; then
+        SINGLE_PARTITION=${1}
+        if [ ! -d "$PARTITION_BASE/${SINGLE_PARTITION}" ] ; then
+            echo "Could not find the partition named ${SINGLE_PARTITION}"
+            exit 1;
+        fi
+    fi
 }
 
 reallystop() {
 	echo "Killing $pid"
 	kill -9 $pid
 }
-# See how we were called.
+
 case "$1" in
   start)
-	start
+	start "$2"
 	;;
   stop)
-	stop
+	stop  "$2"
 	;;
   restart)
-	stop
+	stop "$2"
         sleep 5
-	start
+	start "$2"
 	;;
 esac
 
