support both versioning files (xml.config and raxj.config) in the tarari startup. One script now works for both 3100 6100 cards.
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@17015 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/tarari-initd b/etc/tarari-initd
--- a/etc/tarari-initd
+++ b/etc/tarari-initd
@@ -22,7 +22,14 @@ tarariStart="/usr/local/Tarari/bin/load_xmlcp"
 tarariStop="/usr/local/Tarari/bin/unload_xmlcp"
 USER=`whoami`
 
-RELEASE=`grep label /usr/local/Tarari/config/xml.config | cut -f 2 -d_ | cut -f 1-2 -d .`
+if [ -e  /usr/local/Tarari/config/xml.config ]; then
+    RELEASE=`grep label /usr/local/Tarari/config/xml.config | cut -f 2 -d_ | cut -f 1-2 -d .`
+elif [ -e /usr/local/Tarari/config/raxj.config ]; then
+    RELEASE=`grep label /usr/local/Tarari/config/raxj.config | cut -f 2 -d_ | cut -f 1-2 -d .`
+else
+    echo "could not find any version information for the Tarari installation. Exiting."
+    exit 1
+fi
 
 if [ "$RELEASE" = "4.3" ] || [ "$RELEASE" = "4.4" ]; then
         CARD_ID="0203"
