Process controller now passes arguments to gateway_control script (using -J prefix for JVM options). Script is updated to use exec to avoid unncessary sub-processes. Gateway logging is now sent to stdout/stderr when run using the PC to allow the PC to redirect to a log file when appropriate.
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@20738 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/appliance/configuser_profile b/etc/appliance/configuser_profile
--- a/etc/appliance/configuser_profile
+++ b/etc/appliance/configuser_profile
@@ -80,6 +80,13 @@ do
                     clear;;
                 2)  clear;
                     (${CONFWIZARD});
+                    if [ $? -eq 2 ] ; then
+                      echo "Node is already configured."
+                    elif [ $? -eq 3 ] ; then
+                      echo "Configuration service not available (please reboot)"
+                    elif [ $? -eq 5 ] ; then
+                      echo "Unexpected error in configuration service."
+                    fi
                     echo "Press enter to continue";
                     read;
                     clear;;
