SSG-3061: load_keydata, save_keydata and wipe_keydata should now be safe.
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@23097 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/appliance/load_keydata b/etc/appliance/load_keydata
--- a/etc/appliance/load_keydata
+++ b/etc/appliance/load_keydata
@@ -1,11 +1,12 @@
 #!/bin/sh
+unset PATH
 
 if [ z$1z != zreallyForSurez ]; then
-    echo 'Confirmation argument not present -- aborted' 1>&2
+    /bin/echo 'Confirmation argument not present -- aborted' 1>&2
     exit 3;
 fi
 
 cd /var/opt/sun/sca6000/keydata || exit 1
 
 # This must be the very last line in the file
-tar czf - ssg.*
+/bin/tar czf - ssg.*
