Check for Java 1.6 here, as we don\'t have a package (name), also removed i386 platform check
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@16508 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/solaris_build/pkgbuild/checkinstall b/etc/solaris_build/pkgbuild/checkinstall
--- a/etc/solaris_build/pkgbuild/checkinstall
+++ b/etc/solaris_build/pkgbuild/checkinstall
@@ -1,21 +1,26 @@
 #!/bin/sh
 
 expected_release="5.10"
-expected_platform="i386"
-
+expected_java="1.6"
 release=`uname -r`
-platform=`uname -p`
-
-if [ ${platform} != ${expected_platform} ]; then
-	echo "\n\n\n\tThis package must be installed on a ${expected_platform} architecture\n"
-	echo "\tAborting installation.\n\n\n"
-	exit 1
-fi
 
 if [ ${release} != ${expected_release} ]; then
 	echo "\n\n\n\tThis package must be installed on a ${expected_release} machine\n"
 	echo "\tAborting installation.\n\n\n"
 	exit 1
+fi
+
+if [ -x /usr/j2se/jdk1.6.0_01/bin/java ]; then
+	javaver=`/usr/j2se/jdk1.6.0_01/bin/java -version 2>&1 | awk -F\" '/version/ {print $2}' | awk -F. '{print $1 "." $2}'`;
+	if [ ${javaver} != ${expected_java} ]; then
+		echo "\n\n\n\tThis package requires Java ${expected_java} to be installed in /usr/j2se/jdk1.6.0_01/bin/java\n"
+		echo "\tAborting installation.\n\n\n"
+		exit 1;
+	fi
+else
+	echo "\n\n\n\tThis package requires Java ${expected_java} to be installed in /usr/j2se/jdk1.6.0_01/bin/java\n"
+	echo "\tAborting installation.\n\n\n"
+	exit 1;
 fi
 
 echo Checkinstall exiting happily.
