bugz 3929: the package now interacts with the user properly on install.
here's the sequence of steps

look in the hardcoded location /usr/j2se/jdk1.6.0_01
if there's something there, check the version
if the hardcoded location isn't found or the version found isn't 1.6 prompt the user for a java_home.

since pkg files can accept a response file (silent installs), I also check in checkinstall if the designated location contains a proper JVM

in post install I symlink /ssg/jdk to this location

git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@16725 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/solaris_build/pkgbuild/checkinstall b/etc/solaris_build/pkgbuild/checkinstall
--- a/etc/solaris_build/pkgbuild/checkinstall
+++ b/etc/solaris_build/pkgbuild/checkinstall
@@ -1,69 +1,8 @@
 #!/bin/sh
 
-expected_java_home="/usr/j2se/jdk1.6.0_01"
-expected_java_bin="${expected_java_home}/bin/java"
 expected_release="5.10"
-expected_java_version="1.6"
 release=`uname -r`
-
-MY_JAVA_HOME="${expected_java_home}"
-result=""
-
-#Checks the version of java at the path passed in as an argument
-#	If the argument is a directory, this function will attempt to find java in the bin/ sudirectory
-#	If the argument is not a directory, then it will be used as is to check the version
-#
-#	SIDE EFFECT:
-#		sets result = the location where java was found (suitable for use in JAVA_HOME, i.e. minus the bin/java part)
-# 		or empty if a compatible version of java was not found 
-check_java_version() {
-	basepath=${1}
-	binpath="${basepath}"
-	result=""
-
-	echo "Trying to find java at ${binpath}"
-	if [ ! -f "${binpath}" ] ; then
-		echo "\n\n\n\tNo Java found at ${binpath}"
-		return
-	elif [ -d "${binpath}" ] ; then
-		binpath="${basepath}/bin/java"
-		if [ ! -x "${binpath}" ]; then
-			echo "\n\n\n\tNo Java found at ${basepath} (or ${binpath})"
-			return
-		fi
-	fi
-
-	javaver=`${binpath} -version 2>&1 | awk -F\" '/version/ {print $2}' | awk -F. '{print $1 "." $2}'`;
-	echo "\n\n\n\tFound Java ${javaver} at ${binpath}"	
-
-	if [ "${javaver}" != ${expected_java_version} ]; then
-		echo "\n\n\n\tJava ${expected_java_version} is required \n"
-	else 
-		if [ "${basepath}" = "${binpath}" ] ; then
-			temp=`dirname ${basepath}`
-			result="`dirname ${temp}`"
-		else 
-			result="${basepath}"
-		fi 
-	fi
-}
-#Gets the location of a compatible (1.6) java installation.
-#	If the expected value of ${expected_java_home} is found, and is actually the right version, that will be used
-# 	If ${expected_java_home} is not found then the user is prompted to enter a path, which is checked with check_java_version
-#	SIDE EFFECT: 
-#		Sets MY_JAVA_HOME to the appropriate location
-get_java_location() {
-	result=""
-	while [ "${result}" = "" ]
-	do
-		echo "Please enter the path to a Java ${expected_java_version} installation:"
-		read response
-		check_java_version "${response}"
-	done
-	
-	echo "FOUND a compatible java at ${result}"
-	MY_JAVA_HOME=${result}
-}
+expected_java="1.6"
 
 #Preflight check to ensure that we are even dealing with the right OS revision
 #	Exits early if not
@@ -75,19 +14,23 @@ check_system_release() {
 	fi
 }
 
+check_java_set() {
+    if [ -x "${EXPECTED_JAVA_HOME}" ]; then
+        javaver=`${EXPECTED_JAVA_HOME}/bin/java -version 2>&1 | awk -F\" '/version/ {print $2}' | awk -F. '{print $1 "." $2}'`;
+        if [ ${javaver} != ${expected_java} ]; then
+            echo "\n\n\n\tThis package requires Java ${expected_java} to be installed.\n"
+            echo "\tAborting installation.\n\n\n"
+            exit 1;
+        fi
+    else
+        echo "\n\n\n\tThis package requires Java ${expected_java} to be installed.\n"
+        echo "\tAborting installation.\n\n\n"
+        exit 1;
+    fi
+}
 
 check_system_release
-if [ -x ${expected_java_bin} ]; then
-	check_java_version ${expected_java_bin}
-	if [ "${result}" = "" ]; then
-		get_java_location
-	fi
-else
-	echo "\n\n\n\tThis package requires Java ${expected_java_version} to be installed."
-	get_java_location
-fi
+check_java_set
 
-#write out the location to a file that can be picked up in postinstall
-echo "${MY_JAVA_HOME}" > /tmp/java_is_here
 echo "Checkinstall exiting happily."
 exit 0
