More informative error message when SSG / Enterprise Manager cannot be started due to missing script.
git-svn-id: https://thesource.l7tech.com/thesource/UneasyRooster/trunk@21027 219f1c6e-4a0e-43c8-96f2-6e749be13fd4

diff --git a/etc/enterprisemanager/ssem-initd b/etc/enterprisemanager/ssem-initd
--- a/etc/enterprisemanager/ssem-initd
+++ b/etc/enterprisemanager/ssem-initd
@@ -22,7 +22,10 @@ EM_USER="ssem"
 EM_SCRIPT="/opt/SecureSpan/EnterpriseManager/bin/enterprisemanager.sh"
 
 start() {
-        [ -x "${EM_SCRIPT}" ] || exit 5
+        if [ ! -x "${EM_SCRIPT}" ] ; then
+            echo "Service script not found or not executable."
+            exit 5
+        fi
 
         echo -n $"Starting Enterprise Manager: "
         daemon --check "${PID_FILE}" "${EM_SCRIPT}" "${EM_USER}" "/var/run/${PID_FILE}.pid"
diff --git a/etc/processcontroller/sspc-initd b/etc/processcontroller/sspc-initd
--- a/etc/processcontroller/sspc-initd
+++ b/etc/processcontroller/sspc-initd
@@ -22,7 +22,10 @@ PC_USER="layer7"
 PC_SCRIPT="/opt/SecureSpan/Gateway/controller/bin/processcontroller.sh"
 
 start() {
-        [ -x "${PC_SCRIPT}" ] || exit 5
+        if [ ! -x "${PC_SCRIPT}" ] ; then
+            echo "Service script not found or not executable."
+            exit 5
+        fi
 
         echo -n $"Starting Gateway Services: "
         daemon --check "${PID_FILE}" "${PC_SCRIPT}" "${PC_USER}" "/var/run/${PID_FILE}.pid"
