US347128: DCT: Add remaining static output for network (#81)
* US347128: adding quotes, using logAndRunCmd
* US347128: adding ethtool command, which is the only missing one from the new story's spec
* US347128: adding a space
* US347128: assorted code review feedback

diff --git a/etc/collector/modules/network b/etc/collector/modules/network
--- a/etc/collector/modules/network
+++ b/etc/collector/modules/network
@@ -1,46 +1,41 @@
 #!/bin/sh
 
-MODULE=$1
+MODULE="$1"
 
 # Pull in collector support functions
-. ${COLLECTOR_HOME}/collectorlib
+. "${COLLECTOR_HOME}"/collectorlib
 
 
-preModule $MODULE
-
+preModule "$MODULE"
 
 #Define and create output folders
-NETWORK_MODULE_BaseOutputDirectory=${ALL_MODULES_BASE_OUTPUT_DIR}/${MODULE}
-NETWORK_MODULE_BaseOutputDirectory_config=${NETWORK_MODULE_BaseOutputDirectory}/config
-NETWORK_MODULE_BaseOutputDirectory_logs=${NETWORK_MODULE_BaseOutputDirectory}/logs
-mkdir -p ${NETWORK_MODULE_BaseOutputDirectory}
-#mkdir -p ${NETWORK_MODULE_BaseOutputDirectory_config}
-#mkdir -p ${NETWORK_MODULE_BaseOutputDirectory_logs}
+NETWORK_MODULE_OUTPUTDIR="${ALL_MODULES_BASE_OUTPUT_DIR}/${MODULE}"
+mkdir -p "${NETWORK_MODULE_OUTPUTDIR}"
+if [ ! -w "${NETWORK_MODULE_OUTPUTDIR}" ]
+then
+    echo "Unable to create output directory ${NETWORK_MODULE_OUTPUTDIR}"
+    exit 1;
+fi
 
 #Begin data collection
 
-logCommand ifconfig -a
-ifconfig -a > ${NETWORK_MODULE_BaseOutputDirectory}/ifconfig-a.txt
+logAndRunCmd "ifconfig -a &> \"${NETWORK_MODULE_OUTPUTDIR}\"/ifconfig-a.txt"
+logAndRunCmd "netstat -tnap &> \"${NETWORK_MODULE_OUTPUTDIR}\"/netstat-tnap.txt"
+logAndRunCmd "iptables -nL &> \"${NETWORK_MODULE_OUTPUTDIR}\"/iptables-nL.txt"
+logAndRunCmd "iptables -v -nL &> \"${NETWORK_MODULE_OUTPUTDIR}\"/iptables-v-nL.txt"
 
-logCommand netstat -nr
-netstat -nr > ${NETWORK_MODULE_BaseOutputDirectory}/netstat-nr.txt
-
-logCommand iptables -nL
-iptables -nL  > ${NETWORK_MODULE_BaseOutputDirectory}/iptables-nL.txt
-
-logCommand iptables -v -nL
-iptables -v -nL  > ${NETWORK_MODULE_BaseOutputDirectory}/iptables-v-nL.txt
+for interface in $(ip link show | grep "^[0-9][0-9]*: " | sed 's/^[0-9][0-9]*: //g' | sed 's/: .*$//g')
+do
+    logAndRunCmd "ethtool -S \"${interface}\" &> \"${NETWORK_MODULE_OUTPUTDIR}\"/ethtool-\"${interface}\".txt"
+done
 
 #This command should be run on every node in the cluster.
-logCommand "ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l"
-ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l > ${NETWORK_MODULE_BaseOutputDirectory}/ss_established_inbound_connections.txt
+logAndRunCmd "ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l &> \"${NETWORK_MODULE_OUTPUTDIR}\"/ss_established_inbound_connections.txt"
 
 #This command should be run on every node in the cluster.
-logCommand "ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | grep -v ^0 | egrep -v Recv-Q | wc -l"
-ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | grep -v ^0 | egrep -v Recv-Q | wc -l > ${NETWORK_MODULE_BaseOutputDirectory}/ss_queued_inbound_connections.txt
+logAndRunCmd "ss -o state established \( sport = :8080 or sport = :8443 or sport = :9443 \) \ dst 0.0.0.0/0 | grep -v ^0 | egrep -v Recv-Q | wc -l &> \"${NETWORK_MODULE_OUTPUTDIR}\"/ss_queued_inbound_connections.txt"
 
 #This command should be run on every node in the cluster.
-logCommand "ss -o state established \( dport = :http or dport = :https \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l"
-ss -o state established \( dport = :http or dport = :https \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l > ${NETWORK_MODULE_BaseOutputDirectory}/ss_outbound_connections.txt
+logAndRunCmd "ss -o state established \( dport = :http or dport = :https \) \ dst 0.0.0.0/0 | egrep -v Recv-Q | wc -l &> \"${NETWORK_MODULE_OUTPUTDIR}\"/ss_outbound_connections.txt"
 
-postModule $MODULE
+postModule "$MODULE"
